version: 2

updates:
  # GH Actions updates
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 3
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 14
  # node updates
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 10
      semver-major-days: 30
      semver-minor-days: 12
