name: Jekyll Redirects for Cloudflare
description: Converts a "jekyll-redirect-from" redirect ruleset into one that works on Cloudflare
author: SocksTheWolf

branding:
  icon: arrow-right
  color: green

inputs:
  outputPath:
    description: Your Jekyll build output folder, if you have modified it from the default
    default: '_site'

outputs:
  success:
    description: Outputs if the _redirects was created/updated successfully

runs:
  using: node24
  main: dist/index.js
